### ISSUE TITLE
Extracción de características de audios

### ISSUE THREAD

**Issue by AdrianArnaiz** [AdrianArnaiz/TFG-Neurodegenerative-Disease-Detection#19]
Realización de la extracción de las características de los audios, que seguirá el proceso marcado en el paper _Automatic detection of Parkinson’s disease in running speech spoken in three different languages_ . Para ello serán necesarias varias tareas: 
* [x] Instalación de las librerías de Python necesarias. #13 
* [x] La exploración del funcionamiento de las herramientas. #14  
* [x] El preprocesamiento del audio #15 
  * [x] Eliminar silencios iniciales y finales #15 
  * Dividir en voiced y unvoiced segments [SCRIPTS DISVOICE lo hace internamente]
* [x] La caracterización de los audios (extracción de las medidas en sí mismas)
  * [x] Extraer medidas prosódicas de audios completos #16 
  * [x] Extraer medidas de fonación de Vocales y Running-Speech (voiced segments de frase y palabras) #17 
  * [x] Extraer medidas de articulación: cepstrales y de energía de transiciones (v<->uv) #18

**Comment by AdrianArnaiz** [comment]
A parte de preprocesar y sacar las características (los 3 subsets diferentes) para un audio individual (que devolverá un array para las ccas de ese audio), se necesita recorrer toda la estructura de audios para crear las correspondientes matrices de características (en numpy) de cada tipo de audio y así dejar preparados los datos para entrenar modelos. Hay una matriz de ccas por cada tipo de audio y cada subset de ccas: 3 modelos para reading texts, 3 modelos para monologo, 15 modelo para vocales [3 x vocal) y 3 por cada palabra de la que queramos hacer un modelo (max 25 palabras).

**Comment by AdrianArnaiz** [comment]
Haremos las etapas de preprocesado y modelado del discurso
![image](https://user-images.githubusercontent.com/33413560/55225533-229bc180-5213-11e9-9509-a3ff9f3e4726.png)
